### ISSUE TITLE
Not able to add rounded border to <Video/>

### ISSUE THREAD

**Issue by GorvGoyl** [muxinc/next-video#233]
I would like to add a round border to the `<Video/>`, and I tried using CSS, but it's not working.

```css
mux-player {
   border-width: 2px;
    border-radius: 8px;
}
```
